### PR TITLE
Fix for #200 Optional field with null causes MatchError

### PR DESCRIPTION
**Pull request by noahlz**
See #200

### CODE REVIEW

**Comment by noahlz** [comment]
@niwic here is a candidate fix for this issue. All unit tests pass, but perhaps you could give it a once-over and maybe even compile my branch from source and test locally?  Let me know.

If all looks good we'll release in an upcoming patch version, 1.11.x branch only.

**Comment by niwic** [comment]
I had a look, and ran our integration tests with the snapshot version. The issue seems fixed, so that's nice.

We are, however, now having additional issues with the getAs change in casbah related to querying. A "nested" query on a sub-document (ex. ```"document.subDocument" $gt 1 $lt 10```) will only include the second part of the query. It seems this is only fixable directly in casbah.

**Comment by noahlz** [comment]
Regarding the issues directly fixable in Casbah - since that is a transitive dependency, you can open an issue with them, and when they fix it your project can depend on the version where it's resolved (you might have to use `force()` on the version in your sbt build).

Otherwise, doesn't sound like that blocks merging this?

**Comment by niwic** [comment]
Yup, i have opened an issue with them (https://jira.mongodb.org/browse/CASBAH-201).

I would say you are correct, merging this should be ok.

**Pull request merged**
