### PR TITLE
PR #37 for 1.10.x branch

### PR DESCRIPTION
**Pull request by dieu**
PR #37 for 1.10.x branch

### CODE REVIEW

**Comment by noahlz** [comment]
Noted unit tests failure without this PR:

```
[info] MapSupportSpec
[info] 
[info] a grater should
[info] + support objects that contain maps
[info] ! support complex map
[error]    RuntimeException: : json can't serialize type : class scala.collection.immutable.Map$Map1  (ClassMapBasedObjectSerializer.java:77
)
```

To restate the problem, if a Map has a type `Map[Any, Any]` we should still be able to serialize/deserialize the values.

**Comment by noahlz** [comment]
I am going to make some small changes post-merge:
- elaborate on the test case description, slightly
- Fix deprecation warnings
- Fix erasure warnings

**Comment by noahlz** [comment]
Just published 1.10.0-SNAPSHOT, including this change.

**Comment by dieu** [comment]
@noahlz thanks a lot!

**Comment by noahlz** [comment]
np! Did you see my PR #172 ?

**Pull request merged**
