### PR TITLE
bump Scala versions (2.12.8, 2.11.12, 2.10.7)

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
ping @noahlz

**Comment by noahlz** [comment]
Greetings and thank you for opening a PR!

I don't see a problem with merging this, however I'm unlikely to do a release as minor Scala version bump should not cause a change in binary compatibility with other (or does it....? I'm not up to speed on goings on with Scala 2.12.latest)

Is there a motivation behind this PR - i.e. are you seeing an error on earlier point releases of Scala - or is just a routine "latest and greatest" change?  If it's the former, I'm curious to hear about it.

Sidenote: the Travis CI builds failed for JDK7. Given Java 7 is eol, I'm inclined to just remove those from the build - unless you want to take a crack at fixing that error by tweaking the build configuration? 🙏

**Comment by sullis** [comment]
upgrading the Scala runtime version will upgrade the Scala compiler.

The latest Scala compiler produces more correct bytecode than previous versions of the Scala compiler.

=> Scala 2.12.8 release notes https://github.com/scala/scala/releases/tag/v2.12.8

The benefit of this PR is more correct bytecode in the class files.

**Comment by noahlz** [comment]
Ok, the byte code will be more correct, but will is it currently causing bugz / problems / slowness or such that is impacting a production system? Just want to understand the urgency. I.e. are you waiting on a release?

**Comment by sullis** [comment]
I am planning to migrate my application from JDK8 to JDK11.   My goal is run my application with Scala 2.12.8 on JDK11.  

It would be awesome if this library was compiled with the Scala 2.12.8 compiler.

**Comment by noahlz** [comment]
Ah, travisCI has some failing tests because we still test against jdk7 but it's no longer supported.

travis-ci/travis-ci#8439

I'll merge anyway, and fix the builds to remove jdk7 at some future date. JDK 7 is EOL so there's no reason to support it.

Note that I am not doing a release for this pull request, as typically scala version bumps and I don't have details on what the production impact (performance? bug that's having business impact?) to justify the non-trivial work.

Of course, we do have some outstanding issues in our backlog that, if fixed, could justify a point release. 😉

**Comment by noahlz** [comment]
image

**Pull request merged**
