### PR TITLE
bump casbah to 3.1.1

### PR DESCRIPTION
**Pull request by jvandew**
Hello!

I work on infrastructure at Foursquare. We recently ran into an issue with one of our open source projects using this library after upgrading to version 3 of the mongo-java-driver (that issue is [here](https://github.com/foursquare/fsqio/issues/33)). The immediate fix there to unblock us is to upgrade this library to be compatible with the newer mongo code, and I would like to contribute that back here if others find it useful.

It's worth noting our use of Salat is very minor -- it exists as a one-off in a set of utility scripts used with the Twofishes project, so this has had very little production testing. However, I did run your automated test suite and everything seems in order there.

Let me know if this patch is of interest or if there is any additional work you'd like to see here.

### CODE REVIEW

**Comment by noahlz** [comment]
We're trying to have backwards comparability for now. Does the test suite work with the older version of mongo server?

EDIT: I see that you indeed deleted a bunch of code that is not compatible. I think the case is quickly building for a salat 1.11.x branch with Mongo 3.1+ support.

**Comment by jvandew** [comment]
Ah yes. The test suite does pass when downgraded back to casbah 2, but you presumably had good reason to add those error handling methods with the older version heh.

**Comment by noahlz** [comment]
My personal bias is to support existing code, so I tried my best to support the deprecated error-handling functions that exist in mongo driver 3.0. There are likely a lot of legacy projects out there that might want to upgrade salat (to fix a bug) but can't upgrade Mongo.

**Comment by jvandew** [comment]
That's certainly reasonable. I see in #183 you mentioned mid-February as a possible timeline for starting a 1.11.x release branch, is that still accurate? There is an easy workaround for our open source users so we are not pressed on getting this change out, but if it will be more than a few weeks for a 1.11 release we may just bundle the change with our own code for the time being.

**Comment by noahlz** [comment]
You should go ahead and have your own internal version for now.

**Comment by noahlz** [comment]
I have pushed `1.11.x-branch` which is where scala 2.12 + Casbah 3.1.x support will reside. 

As such, I updated the target branch to 1.11.x-branch.

Motivation: I want to maintain support for Scala 2.10.x + Casbah 2.7.2 on `1.10.x-branch`

**Comment by noahlz** [comment]
@jvandew I published `1.11.0-SNAPSHOT` which requires scala 2.12.  

If you are still on 2.11 and that's what you need, I'm going to walk back my attempt to support 2.12 and have Salat 1.11 be just about upgrading Casbah.  Looking for your feedback.

**Comment by pferrel** [comment]
+1 (as I understand above) 

I would like Mongo 3.x, Casbah 3.x and am using Scala 2.11. IMO this may be where many users are. I haven't seen much pressure to move to Scala 1.12 yet.

Ready to test if there is a branch, PR, or lib.

**Comment by noahlz** [comment]
Yeah this is my bad, sorry. I got too ambitious trying to upgrade both scala 2.12 and casbah 3.1.1 at once. #183 

I published a snapshot version of 2.12 + casbah 3.1.1 only, because it doesn't cross compile with 2.11 for aforementioned reasons.  My plan of action is to walk back the 2.12 support (we'll save that for salat 2.0 someday, perhaps...) and revert to 2.11 + 3.1.1 on the `1.11.x-branch`

Further updates in #183

**Comment by jvandew** [comment]
Sorry for the delay, you caught me over vacation :)

We are still on scala 2.11, so no problems on our end there. Thanks for your help!

**Comment by pferrel** [comment]
Sorry, a bit round about as I learn your contribution process. It's here: https://github.com/salat/salat/pull/191

Now we'll see if it passes travis. I doubt my edits of the README are correct or complete

**Comment by pferrel** [comment]
@noahlz @jvandew is the PR here: https://github.com/salat/salat/pull/191 ok for  start?

`sbt test:test` has no errors with scala 2.11 and casbah 3.x on my machine. Took a shot at .travis and README but the later needs a more experienced eye for published location and version numbers

**Comment by pferrel** [comment]
Also should we consolidate comments somewhere, like the PR?

**Comment by noahlz** [comment]
I don't mind having comments across multiple related issues + PRs as long as they are referenced to each other via linking (which we're doing).

**Comment by pferrel** [comment]
Ok, but I'm a bit confused so maybe we can move to  https://github.com/salat/salat/pull/191

**Comment by noahlz** [comment]
Yes, let's - esp since this PR was merged.

**Pull request merged**
