### PR TITLE
Failed test case that deserializes JSON having null value into case class with Option[String] field

### PR DESCRIPTION
**Pull request by panshin**

### CODE REVIEW

**Comment by panshin** [comment]
Relative to this issue https://github.com/salat/salat/issues/113

May be im missing something?

**Comment by noahlz** [comment]
This is failing a test.

```
[info]     x simple type with null
[error]        'Gustav(Some(Some(null)))' is not equal to 'Gustav(None)' (JsonSpec.scala:404)
[error] Expected: Gustav(None)
[error] Actual:   Gustav(Some(Some(null)))
```

Roughly the `null` is parsed into a `Some(null)` rather than a None.  With default arguments suppressed, you would have to provide `{ }` instead of `{ "o" : null }` for the value of the `o` to be resolved to `None`.

The original issue #113 was a request from the submitter for Salat to work differently, that is, to coerce `null` to `None` always.

**Comment by noahlz** [comment]
Further down in the same file we have the following test:

```
grater[Gustav].fromJSON(JObject(Nil)) must_== Gustav(o = None)
```

The definition of `Gustav`

```
case class Gustav(o: Option[String] = None)
```

We also have a number of tests proving that a `Double` field can be serialized as `null` as I imagine other non-`Option` fields can.  However, when you have an `Option[A]` field (where `A` is some type) things get tricky. How do you distinguish `Some(null)` from None?  

see https://stackoverflow.com/questions/5796616/why-somenull-isnt-considered-none

**Comment by noahlz** [comment]
I'm unable to reproduce with a simple addition to my [salat-examples](https://github.com/noahlz/salat-examples) app, so it might be something specific to the test suite (i.e. the context configuration) or a minor detail of your test that we have overlooked.

This works as expected:
```
case class OptionHolder(foo: Option[String] = None)

scala> import salat._
import salat._

scala> import salat.global._
import salat.global._

scala> val o = OptionHolder(None)
o: com.novus.salat.examples.OptionHolder = OptionHolder(None)

scala> grater[OptionHolder].toCompactJSON(o)
res0: String = {}

scala> grater[OptionHolder].fromJSON("""{ "o": null }""")
res1: com.novus.salat.examples.OptionHolder = OptionHolder(None)
```

What do you think @Panshin ?

**Comment by noahlz** [comment]
@Panshin do you think this is the same issue as #200, namely a change in how casbah handles `null` fields?

**Comment by noahlz** [comment]
Related:

https://stackoverflow.com/questions/12403240/storing-null-vs-not-storing-the-key-at-all-in-mongodb

https://stackoverflow.com/questions/21120999/representing-null-in-json

**Comment by noahlz** [comment]
I'm starting to look into this issue on this branch and make changes if you want to follow along / contribute:

noahlz/salat@42d5437

Didn't quite get to the bottom of this yet, but found another issue related to non-option fields.

My finding so far is that Salat is opinionated about the format JSON output, namely it expects to omit `None` values.  `Gustav(None)` should emit `{}` rather than `{ "o" : null }`, and likewise Salat expects the input JSON string to be similar: `{}` not `{"e": null}` for `Gustav(None)`

A possible work-around is to create a custom transformer.

Fixing it Salat might involve having the `Grater` recognize when an incoming parsed JSON value is actually a `JNull` and map that directly to `None`.  We might consider requiring `JSONConfig.outputNullValues = true` to support such behavior.

**Comment by noahlz** [comment]
@Panshin  thank you for this issue. I cherry-picked onto another branch in my repo, and when it is fixed / merged into the main branch, that should close this PR.

**Comment by noahlz** [comment]
Note to self: this is superseded by #205

**Pull request closed without merging**
