### PR TITLE
Upgrade Casbah to 2.8.2

### PR DESCRIPTION
**Pull request by danslapman**
This PR upgrades Casbah to 2.8.2 (#145)
I also fixed usages of deprecated getCachedLastError

### CODE REVIEW

**Comment by noahlz** [comment]
Thank you for this contribution!

**Comment by danslapman** [comment]
Will it ever be merged? Casbah 3.0 is already out!

**Comment by rcaloras** [comment]
:+1:

**Comment by martende** [comment]
:+1:

**Comment by sief** [comment]
+1

**Comment by sief** [comment]
Mongodb will sunset support for MongoDB 2.6 at the end of October, 2016: https://www.mongodb.com/blog/post/mongodb-2-6-end-of-life

Are there any plans to merge this until then?

**Comment by noahlz** [comment]
My proposed plan is to merge this into a forthcoming `1.10.x-branch` and subsequent `1.10.x` release in coming weeks. See my recent comments on #160

**Comment by noahlz** [comment]
Salat 1.10.0-SNAPSHOT, which includes the commits from this PR, is now available!

**Comment by noahlz** [comment]
PS Sincere apology for the painful delay! As an OSS consumer myself, I know how much it sucks when you find a project that doesn't have movement on it for a while.

**Comment by noahlz** [comment]
All - this PR has been cherry-picked into the `1.10.x-branch` and when `1.10.0` is officially released I will close this PR (without merging, even though the commits will be in there).

There is some discussion happening over in #158 regarding this change, please hop over there if you want to contribute to the discussion.

**Comment by noahlz** [comment]
This PR is superseded by #168 and/or #170 (which will attempt to provide some semblance of support for legacy code that uses `MongoConnection`.

Please join the further discussion over there and/or on the issue, #158.

**Pull request closed without merging**
