### PR TITLE
Scala 2.11 casbah 3.x

### PR DESCRIPTION
**Pull request by pferrel**

### CODE REVIEW

**Comment by pferrel** [comment]
If merged is this published somewhere as a jar? If so I'm unsure what the resolver and sbt lib entry should be for testing. I tried to guess at it but it was not resolved at link time.

**Comment by noahlz** [comment]
It's not yet - apologies - I'm not set up to publish at the moment, I'll be able to do it tonight or tomorrow afternoon.

**Comment by pferrel** [comment]
No problem at all. I'm happily working with the previous version for now. Just ping me when you want me to test and many thanks.

**Comment by noahlz** [comment]
Hello - the `1.11.0-SNAPSHOT` should be available (I published it last Sunday) - let me know if it looks good and I'll formally release this weekend. Thanks!

**Pull request merged**
